services:
  - type: web
    name: faceface-app
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      # Auth0 variables for Google Login (REQUIRED - see AUTH0_SETUP_GUIDE.md)
      - key: AUTH0_DOMAIN
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: AUTH0_CALLBACK_URL
        sync: false
    healthCheckPath: /test

